version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: course-postgres
    restart: always
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: course-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
