version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: course-postgres
    restart: always
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: service_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: course-redis
    restart: always
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: ../..
      dockerfile: app/Dockerfile
    container_name: course-fastapi
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://service:service@postgres:5432/service_db
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - postgres
      - redis
    restart: always

  celery:
    build:
      context: ../..
      dockerfile: celery/Dockerfile
    container_name: course-celery
    environment:
      - DATABASE_URL=postgresql://service:service@postgres:5432/service_db
      - REDIS_URL=redis://localhost:6379
    depends_on:
      - postgres
      - redis
    restart: always

volumes:
  postgres_data:
    driver: local
